### ISSUE TITLE
Need complete functional testing for correct error handling

### ISSUE THREAD

**Issue by ned14** [BoostGSoC13/boost.afio#10]
Right now, the unit and functional testing mostly tests success. For any library which can cause data loss like this one, very robust error handling functional testing is needing. I'm think that as an absolute minimum we need to mount a filing system via a looped back file and intentionally test out of disc space error handling on it for correctness.

Other idea is to deliberately bitflip corrupt the loopback file to test how we handle weird filing system errors.

**Comment by ariccio** [comment]
[Relevant? "Understanding the Robustness of SSDs under Power Fault"](https://www.usenix.org/conference/fast13/technical-sessions/presentation/zheng)

**Comment by ariccio** [comment]
(because of the testing, not the drive deaths)

**Comment by ned14** [comment]
Mmm. The reason I closed this issue here is because this sort of testing doesn't really belong in AFIO. AFIO is plain dumb - it doesn't try to second guess either the app or the OS, well except in doextents on POSIX maybe. TripleGit is the right place for this sort of testing.
