### ISSUE TITLE
Question regarding AFIO / and serialization of directory enumeration / reads?

### ISSUE THREAD

**Issue by vade** [BoostGSoC13/boost.afio#122]
Hello

Firstly AFIO is amazing, thank you for the library. On OS X I am able to with some fiddling get sustained full disk saturation (800MB/s on my Mac Book Pro), although I am having some issues / concerns.

I am wondering how to use AFIO for serializing director enumeration / file reading.

My use case is that I have a directory of files I wish to read completely and load into a circular buffer for use another thread.

My code is roughly structured as follows:

// we have enumerated our directory and cached directory_entries into a vector.

                afio::future<> openfile = afio::async_file(enumeration, i.name(), afio::file_flags::read | afio::file_flags::will_be_sequentially_accessed | afio::file_flags::os_direct);

                // Async Open, upon completion run following code, capture everything by
                openfile.then([=] (afio::future<> &openfile)
                {
                        // set up buffers to for the read

                        // async read
                        afio::future<> read(afio::async_read(openfile, latestAvailableBufferRef->getData(), latestAvailableBufferRef->getSize(), 0));
                        
                        // once our read completes, write to our buffer
                        read.then([=](afio::future<> &read)
                        {
                            // Append to our circular buffer
                             afio::async_close(openfile);
                        });
                    }
                });

I realize that the above mechanism makes no real guarantee that the open.then, and read.then will return serially, meaning a guarantee that reads happen in the order open enumerated.

Are there mechanisms to guarantee enumerated opening of files without forcing some sort of semaphore / block to wait for a read?

I've seen the dispatcher, but I'm unclear if that is of use here.

Thank you for your input!

**Comment by ned14** [comment]
> Are there mechanisms to guarantee enumerated opening of files without forcing some sort of semaphore / block to wait for a read?

There is no mechanism - the OS will open the files in some random order, and moreover each of the reads will also happen in a completely different random order.

Your solution above is likely optimally fast, but will use a ton of memory. I'd suggest you only use memory allocation for small files less than 64Kb and use memory maps for the rest. AFIO will memory map a file for you using the map_file() function off of afio::handle. That lets the OS figure out by itself how much RAM to spend on reading your files optimally.

If you do use memory maps, you might want to turn off os_direct. In fact, you may find turning off os_direct is faster above overall as the file system driver usually has very limited concurrency (about 30 on Windows, about 1 on Linux) normally hidden for you by the page cache layer.

os_direct is great if you have a single file you do a lot of i/o with, it's surprisingly bad if you ever open or close files. I don't think it's a use case optimised by the kernel folk.

Niall

**Comment by vade** [comment]
Hi Niall

Thank you so much for the prompt feedback. I appreciate that these concerns also are not in particular issues with AFIO, but properly implementing it along with understanding file system and I/O concepts.

Is there a better place to direct questions regarding AFIO, correct use, and optimization?

Thank you again for the library and information.

**Comment by ned14** [comment]
> Thank you so much for the prompt feedback. I appreciate that these concerns also are not in particular issues with AFIO, but properly implementing it along with understanding file system and I/O concepts.

There is a real lack of documentation on real world filing system and OS behaviour. I have a ton in my head, but I'd much rather it be written into a suite of test tools which submit empirical results into a public database. Time and resources as always :(

> Is there a better place to direct questions regarding AFIO, correct use, and optimization?

I think stackoverflow is probably best. If you tag the question boost-afio, I should spot it and reply.
