### ISSUE TITLE
AFIO release build compilation errors on Visual Studio 2015

### ISSUE THREAD

**Issue by vade** [BoostGSoC13/boost.afio#123]
Hello

asio.hpp include fails to build under default release mode with Visual Studio 2015 for some reason. Debug builds work. I attempted to disable whole program optimization and code optimization as a work around, but still get the error. I am unable so far to isolate a particular build, linker or C++ flag in VisualStudio that triggers the issue.

The errors are as follows:

\boost\afio\v2\detail\impl\../../afio.hpp(1601): fatal error C1001: An internal error has occurred in the compiler.
1>  (compiler file 'msc1.cpp', line 1393)
1>   To work around this problem, try simplifying or changing the program near the locations listed above.
1>  Please choose the Technical Support command on the Visual C++
1>   Help menu, or open the Technical Support help file for more information
1>  INTERNAL COMPILER ERROR in 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\x86_amd64\CL.exe'
1>      Please choose the Technical Support command on the Visual C++
1>      Help menu, or open the Technical Support help file for more information
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

The error appears focused around

  //! Schedules a callable to be invoked after this future becomes ready. If this future is null, use the current async file i/o dispatcher.
    template<class U> auto then(U &&f) -> typename detail::continuation_return_type<decltype(f(*this))>::future_type
    {
      using future_type = typename detail::continuation_return_type<decltype(f(*this))>::future_type;
      using promise_type = typename detail::continuation_return_type<decltype(f(*this))>::promise_type;
      return detail::do_continuation<future_type, promise_type>()(parent(), this, std::forward<U>(f));
    }

To note, under Clang /LLVM via Xcode 6.2 and better, there are no compilation issues under debug and release out of the box, nor any settings to tweak.

Thank you!

**Comment by ned14** [comment]
> asio.hpp include fails to build under default release mode with Visual Studio 2015 for some reason. Debug builds work. I attempted to disable whole program optimization and code optimization as a work around, but still get the error. I am unable so far to isolate a particular build, linker or C++ flag in VisualStudio that triggers the issue.

This is highly surprising given https://ci.nedprod.com/job/Boost.AFIO%20Build/ which builds everything with release.

Could it be the whole program optimisation?

I'm hesitant to try fixing VS2015 until Update 1 ships which I suspect will fix the problem.

**Comment by vade** [comment]
In attempting to resolve the issue last night, I tried switching as many obvious Release mode configuration options that are different when compared to Debug build via the All Configurations and then viewing <Different Options>, to no avail. Yes, I tried disabling Whole Program Optimization.

What is interesting is the code failure seems to be related to futures use in my client code of AFIO/. Disabling the inclusion of the following code (which I isolated by manual binary search ) allows compilation to work on Visual Studio 2015. Note, VS 2015 has experimental C++17 support, which someone smarter than I indicated may change some guarantees on Futures, which might be at play here?

Note clang/llvm has no issue under Xcode, but I am compiling with C++11 via Clang.



	afio::future<> openfile = afio::async_file(enumerator, i.name(), afio::file_flags::read | afio::file_flags::will_be_sequentially_accessed);// | afio::file_flags::os_direct);

	openfile.then([=](afio::future<> &openfile) {});

 
The openfile.then call didn't work with my actual callback / then. Simplifying it to this state causes the compiler crash. Removing the openfile.then completely resolve the issue, assuming I have no other futures in use from AFIO. I'll see if I can change the C++ Dialect in VS.

**Comment by vade** [comment]
So, one cannot change the VS C++ Dialect - its part of the working toolchain - v140 in this case. As an experiment I installed VS 2013 Update 5 only to error on compiler errors not support __cpp_noexcept, _cpp_thread_local, etc. 

I'll continue to update as I try solution. Thanks.

**Comment by vade** [comment]
Ok, interesting!

I can get it to compile if I don't use the capture all automatic variables by value.

openfile.then([=](afio::future<> &openfile) {});
 
to

openfile.then([](afio::future<> &openfile) {});

Compiles. Interesting.

**Comment by ned14** [comment]
Definitely a compiler bug, almost certainly fixed in Update 1 which releases any day now.

Microsoft were a bit quick shipping VS2015.

**Comment by vade** [comment]
Ah. Ive just tried 2015 Update 1 RC - no joy. This seems super strange. I appreciate your responses. Seems pretty clear this is a compiler edge case. Ill continue to investigate.

**Comment by ned14** [comment]
Did you try the new clang toolset built into 2015 Update 1? This uses clang instead of MSVC, yet is fully Windows compatible.
