### ISSUE TITLE
`buffer` created with `sizeof(FILE_ALL_INFORMATION)/sizeof(std::filesystem::path::value_type)+32769`, then cast to (FILE_ID_FULL_DIR_INFORMATION *)

### ISSUE THREAD

**Issue by ariccio** [BoostGSoC13/boost.afio#64]
In `afio.ipp`, at 2116, `std::filesystem::path::value_type buffer` is initialized with the statement:

    BOOST_AFIO_TYPEALIGNMENT(8) std::filesystem::path::value_type buffer[sizeof(FILE_ALL_INFORMATION)/sizeof(std::filesystem::path::value_type)+32769];

And then on 2122, it's cast to a `(FILE_ID_FULL_DIR_INFORMATION *)`. Is this intended?

A `static_assert( sizeof( FILE_ID_FULL_DIR_INFORMATION ) == sizeof( FILE_ALL_INFORMATION ), "different sizes!" );` fails on my end.

Looking at `FILE_ALL_INFORMATION` and `FILE_ID_FULL_DIR_INFORMATION` has me concerned ( but not certain due to alignment weirdness ) that this might not yield valid data. `CreationTime` for example, is the third field in `FILE_ID_FULL_DIR_INFORMATION`, but the first in `FILE_ALL_INFORMATION` - they're both file times, so I think it's plausible that if true, this might've been missed in testing.

**Comment by ned14** [comment]
Yep that should have been:

            BOOST_AFIO_TYPEALIGNMENT(8) filesystem::path::value_type buffer[sizeof(FILE_ID_FULL_DIR_INFORMATION)/sizeof(filesystem::path::value_type)+32769];

As it happens, sizeof(FILE_ALL_INFORMATION)>sizeof(FILE_ID_FULL_DIR_INFORMATION), so this bug is thankfully benign.

Fixed this end, thanks for the report. It should push to develop later today along with the new sparse file support.
