### ISSUE TITLE
SAL in nt_kernel_stuff is commented out?

### ISSUE THREAD

**Issue by ariccio** [BoostGSoC13/boost.afio#65]
All of the annotations in [nt_kernel_stuff](https://github.com/BoostGSoC13/boost.afio/blob/master/include/boost/afio/detail/impl/nt_kernel_stuff.hpp#L139) are commented out....what's up with that?

Is it a MinGW thing? I think you can include `nosal.h`?

**Comment by ned14** [comment]
Boost doesn't permit macros prefixed with an underscore as those are reserved in the C++ standard.
