### ISSUE TITLE
Hello World example is buggy

### ISSUE THREAD

**Issue by bravnsgaard** [BoostGSoC13/boost.afio#70]
The Hello World example has a bug in the `try`-block:
```
boost::afio::async_path_op_req req("example_file.txt",
                                   boost::afio::file_flags::ReadWrite);
```
Another *file flag* is needed for correct operation: `file_flags::Create` or maybe `file_flags::CreateOnlyIfNotExists`. Otherwise the file is never created and the rest of the example is garbage.

**Comment by ned14** [comment]
Fixed
