### ISSUE TITLE
Boost.Monad link broken

### ISSUE THREAD

**Issue by viboes** [BoostGSoC13/boost.afio#89]
The link to Boost.Monad [1] is broken in https://boostgsoc13.github.io/boost.afio/doc/html/afio/overview.html.

[1] https://ci.nedprod.com/job/Boost.Spinlock%20Test%20Linux%20GCC%204.8/doxygen/group__future__promise.html

**Comment by ned14** [comment]
Thanks for this. It's already fixed in 0d8c232bd3e9b4f7ecf0079f77091e16353ed239.
